---
- name: install war.file
  hosts: web
  become: yes

  tasks: 
  - name: Ensure maven package is present
    apt: 
      name: maven
      state: present

  - name: Ensure git package is present
    apt: 
      name: git
      state: present

  - name: Ensure default-jdk  package is present
    apt: 
      name: default-jdk
      state: present

  - name: Git clone
    git:
      repo: 'https://github.com/kekcment/calculator-servlet-example.git'
      dest: /tmp/calculator-servlet-example
      clone: yes

  - name: Check war is result.stat.exists
    stat:
      path: /tmp/calculator-servlet-example/target/mycalcwebapp.war
    register: result

  - name: Build Maven artifact
    command: mvn --batch-mode --quiet install
    args:
      chdir: /tmp/calculator-servlet-example/
    when: not result.stat.exists  

  - name: Specifying a destination path
#    fetch:
    synchronize:
      src: /tmp/calculator-servlet-example/target/mycalcwebapp.war
      dest: /tmp/calculator-servlet-example/
#      flat: yes
    when: not result.stat.exists 

- name: war prodaction
  hosts: db
  become: yes

  tasks: 
  - name: Ensure tomcat9 package is present
    apt: 
      name: tomcat9
      state: present

  - name: Ensure default-jdk  package is present
    apt: 
      name: default-jdk
      state: present

  - name: Copy war file
#    copy:
    synchronize:
      src: /tmp/calculator-servlet-example/mycalcwebapp.war
      dest: /var/lib/tomcat9/webapps/       