---
- name: install maven
  hosts: web
  become: yes

  tasks: 
  - name: Ensure maven package is present
    apt: 
      name: maven
      state: present

  - name: Ensure git package is present
    apt: 
      name: git
      state: present

  - name: Ensure default-jdk  package is present
    apt: 
      name: default-jdk
      state: present

  - name: Ensure default-jdk  package is present
    apt: 
      name: default-jdk
      state: present

  - name: Git clone
    git:
    repo: 'https://github.com/kekcment/calculator-servlet-example.git'
    dest: /tmp/calculator-servlet-example
    clone: yes

  - name: Build Maven artifact
    command: mvn --batch-mode --quiet install
    args:
     chdir: /tmp/calculator-servlet-example/

  - name: Specifying a destination path
    ansible.builtin.fetch:
    src: /tmp/calculator-servlet-example/target/mycalcwebapp.war
    dest: /tmp/calculator-servlet-example/
    flat: yes

---    